name: Main Workflow
on: [push]
jobs:
  PHPCS:
    name: Run PHPCS
    runs-on: ubuntu-latest
    steps:
    - uses: rtCamp/action-phpcs-code-review@v1.0.0
      with:
        secrets: ${{ secrets.BOT_TOKEN }}
