name: PHP Composer

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run phpcs
      run: ./vendor/bin/phpcs

    - name: Require readme change for new classes
      run: |
        NEW_FILES=$(git diff --name-status develop | grep '^A' | wc -l)
        if [[ ${NEW_FILES} -gt 0 ]]; then
            # see if README is updated
            README_CHANGES=$(git diff --name-status README.md | grep '^M' | wc -l)
            if [[ ${README_CHANGES} -eq 0 ]]; then
                # comment on the PR?
                echo "should have a readme change"
            fi
        fi

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
